name: Smoke Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" >> $GITHUB_OUTPUT

      - name: Cache Playwright
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright and dependencies
        run: npx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Install only Playwright dependencies
        run: npx playwright install-deps chromium
        if: steps.playwright-cache.outputs.cache-hit == 'true'

      #- name: Run Playwright tests
      #  run: npm run smoke:ci --silent > smoke-results.json || true

      #- name: Install ffmpeg
      #  run: sudo apt-get update && sudo apt-get install -y ffmpeg

      #- name: Generate markdown report
      #  run: node scripts/gen-smoke-report.js

      #- name: Commit markdown report
      #  run: |
      #    git config --global user.email "ci@github.com"
      #    git config --global user.name "CI"
      #    git add SMOKE-REPORT.md smoke-outputs*
      #    git commit -m "Update smoke report [ci skip]" || echo "No changes"
      #    git push

      - name: Gerar relatório HTML
        run: npx playwright test --reporter=html || true

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          force_orphan: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
